version: '{build}'
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
  - nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
  - nuget sources Add -Name aspnetmaster -Source https://www.myget.org/f/aspnetmaster/api/v3/index.json
  - nuget sources Add -Name myget -Source https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
  - nuget sources Add -Name aspnetci -Source https://www.myget.org/F/aspnetcidev/api/v3/index.json
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\src\MvcDeviceDetector\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 98ef5401-34d4-4795-9e72-d657e335c3c8
  on:
    branch: master
    appveyor_repo_tag: true
clone_depth: 1
